/**
 * OnlyAuth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetApps200ResponseAppsInner from './GetApps200ResponseAppsInner';

/**
 * The GetApps200Response model module.
 * @module model/GetApps200Response
 * @version 0.1.2
 */
class GetApps200Response {
    /**
     * Constructs a new <code>GetApps200Response</code>.
     * @alias module:model/GetApps200Response
     */
    constructor() { 
        
        GetApps200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetApps200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetApps200Response} obj Optional instance to populate.
     * @return {module:model/GetApps200Response} The populated <code>GetApps200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetApps200Response();

            if (data.hasOwnProperty('apps')) {
                obj['apps'] = ApiClient.convertToType(data['apps'], [GetApps200ResponseAppsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetApps200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetApps200Response</code>.
     */
    static validateJSON(data) {
        if (data['apps']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['apps'])) {
                throw new Error("Expected the field `apps` to be an array in the JSON data but got " + data['apps']);
            }
            // validate the optional field `apps` (array)
            for (const item of data['apps']) {
                GetApps200ResponseAppsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/GetApps200ResponseAppsInner>} apps
 */
GetApps200Response.prototype['apps'] = undefined;






export default GetApps200Response;

