/**
 * OnlyAuth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ValidateSuccessToken200Response model module.
 * @module model/ValidateSuccessToken200Response
 * @version 0.1.2
 */
class ValidateSuccessToken200Response {
    /**
     * Constructs a new <code>ValidateSuccessToken200Response</code>.
     * @alias module:model/ValidateSuccessToken200Response
     */
    constructor() { 
        
        ValidateSuccessToken200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ValidateSuccessToken200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidateSuccessToken200Response} obj Optional instance to populate.
     * @return {module:model/ValidateSuccessToken200Response} The populated <code>ValidateSuccessToken200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidateSuccessToken200Response();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('end_user_uuid')) {
                obj['end_user_uuid'] = ApiClient.convertToType(data['end_user_uuid'], 'String');
            }
            if (data.hasOwnProperty('end_user_phone_number')) {
                obj['end_user_phone_number'] = ApiClient.convertToType(data['end_user_phone_number'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ValidateSuccessToken200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ValidateSuccessToken200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is a string
        if (data['end_user_uuid'] && !(typeof data['end_user_uuid'] === 'string' || data['end_user_uuid'] instanceof String)) {
            throw new Error("Expected the field `end_user_uuid` to be a primitive type in the JSON string but got " + data['end_user_uuid']);
        }
        // ensure the json data is a string
        if (data['end_user_phone_number'] && !(typeof data['end_user_phone_number'] === 'string' || data['end_user_phone_number'] instanceof String)) {
            throw new Error("Expected the field `end_user_phone_number` to be a primitive type in the JSON string but got " + data['end_user_phone_number']);
        }

        return true;
    }


}



/**
 * The validated success token (TOKN-XXX)
 * @member {String} token
 */
ValidateSuccessToken200Response.prototype['token'] = undefined;

/**
 * Supplied uuid of the end user
 * @member {String} end_user_uuid
 */
ValidateSuccessToken200Response.prototype['end_user_uuid'] = undefined;

/**
 * Supplied phone number of the alleged end user
 * @member {String} end_user_phone_number
 */
ValidateSuccessToken200Response.prototype['end_user_phone_number'] = undefined;






export default ValidateSuccessToken200Response;

